### ISSUE TITLE
Cross-compile to both Scala 2.10 / 2.11

### ISSUE THREAD

**Issue by ogirardot** [groupon/sparklint#18]
For now it seems to be compiled only against 2.10 and Spark's default is rather 2.11 now.
Do you wish to migrate to sbt, I can open a PR that way and fix this (+ prepare work for sonatype publication)

**Comment by swhitear** [comment]
Great to see you here Olivier!
@roboxue what do you think?  I have no attachment to mvn, it's a habit we pulled over from Grpn, sbt more typical and has decent mvn support anyway.
@ogirardot I'd go with the PR, but would like Robert's thoughts before a merge.

**Comment by roboxue** [comment]
No attachment to mvn at all.  @ogirardot I'd love to see your sbt version PR!

The pros and cons from my point of view so far are:

- The most challenge things right now is supporting multiple spark versions. i.e in Spark 1.6 there is an `RDD.getNumPartitions` call, while in Spark 1.5 you have to do `RDD.partitions.length`; I'm not knowledgable enough to figure out how to do that in either maven or sbt. Whichever can solve this library versioning problem will be the winner!
- We are not relying on anything in scala 2.11, it simply works with mvn sans cross compile, so I'm currently going with the more mature and familiar one.
- There is no cmd line trick in sbt in order to skip tests, (sbt file has to be updated). Thus the modify -> start server dev flow in Intellij is slower. This is a minor "developer experience" blocker IMO. I know you can also change the sbt file first when doing UI work then revert, but it requires human labor to change the sbt file back and forth, (and keep an eye on not to check in the changes). I might be missing some well known tricks here, feel free to point out!
