### ISSUE TITLE
Spark 2 support

### ISSUE THREAD

**Issue by hoesler** [groupon/sparklint#37]
I started working on a [Spark 2 compatible version of sparklint](https://github.com/hoesler/sparklint/tree/spark2), based on the sbt branch. So far I only tested it with live monitoring of a spark-shell, but that looks good.

Apart from Spark 2 adjustments (mainly matrics API related), the code changes include some bug fixes and temporary workarounds.

Are you interested in adding a Spark2 branch? I am happy to send a pull request.

**Comment by roboxue** [comment]
Yes I'll start testing Spark2 soon. Groupon just started evaluating Spark2.0 very recently, and getting Sparklint working with 2.0 is on the way. I'm still busy reading SBT references these days trying to find a better solution to target different spark versions, since the developer apis are volatile to change from versions to versions. The develop branch will be spark 1.6.1 for a while before the build system switches completes.

When reading your branch, I see some interesting hack that I can't figure out the reason yet without reading Spark2.0's metrics code. Please merge latest develop branch into your branch, which covers some fixes in your branch as well like the filename case issue and object structures, and then open a PR, so we can keep tracking on this topic after I got more time to play with sbt and Spark 2.0. I'll very likely push Spark 2.0 related changes to another temporary branch before the sbt switch over.

**Comment by hoesler** [comment]
Great. I'll send you the PR.

Regarding the "interesting hack": I'm not sure what you are referring to. But one thing I noticed, is that the `CompressedMetricsSink` assumes validity of some preconditions, but does not check them. For example `getBucketIndex` uses a long to int conversion, but does not check for overflow. I noticed it, because the event source start time (origin) was not properly set (=0) and the bucket index `(end - start > Integer.MAX_VALUE).toInt` became negative.
